apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-app.fullname" . }}
  labels:
    {{- include "hello-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5678
      name: http
  selector:
    {{- include "hello-app.selectorLabels" . | nindent 4 }}