name: Deploy Helm Chart to EKS - Multi-environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Create namespace if not exists
      run: |
        kubectl get ns ${{ github.event.inputs.environment }} || kubectl create ns ${{ github.event.inputs.environment }}

    - name: Deploy using Helm
      run: |
        helm upgrade --install http-echo-${{ github.event.inputs.environment }} ./charts/http-echo \
          --values env/${{ github.event.inputs.environment }}-values.yaml \
          --namespace ${{ github.event.inputs.environment }} \
          --create-namespace
